input/vocabulary/valueset-organization-affiliation-role.json, input/vocabulary/valueset-practice-setting-code.json
Exapnded valuesets from Firely server
=> Added required valuesets for organization affiliation

input/vocabulary/valueset-program.json, input/vocabulary/valueset-service-category.json, input/vocabulary/valueset-service-provision-conditions.json, input/vocabulary/valueset-service-referral-method.json, input/vocabulary/valueset-service-type.json
Expanded valuesets manually and from Firely server
=> Added valuesets for Healthcare Service

input/vocabulary/valueset-organization-affiliation-role.json
Updated the expansion with system on the organization affiliation role.
=> Updated the expansion with system on the organization affiliation role.

input/vocabulary/valueset-address-fips-county-colorado.json
Patient county valuesets is updated with a leading-zero to the codes in the valuesets compose and expansion elements.
=> Updated valueset-address-fips-county-colorado

input/vocabulary/valueset-languages.json, input/vocabulary/valueset-qualification-code.json
Hi @enjoysparkling ,
Creating the Pull request, Kindly review.
=> Value sets for the Practitioner profile

input/vocabulary/valueset-device-action.json, input/vocabulary/valueset-device-kind.json, input/vocabulary/valueset-event-status.json, input/vocabulary/valueset-performer-role.json, input/vocabulary/valueset-procedure-category.json, input/vocabulary/valueset-procedure-followup.json, input/vocabulary/valueset-procedure-not-performed-reason.json, input/vocabulary/valueset-procedure-outcome.json, input/vocabulary/valueset-us-core-procedure-code.json
@enjoysparkling Hi Matt, Kindly review the pull request.
=> Value sets for the Procedure profile

input/vocabulary/valueset-diagnosis-role.json, input/vocabulary/valueset-episode-of-care-status.json, input/vocabulary/valueset-episode-of-care-type.json
=> Added Episode of care valuesets

input/vocabulary/valueset-service-request-intent.json, input/vocabulary/valueset-service-request-order-detail.json, input/vocabulary/valueset-service-request-priority.json, input/vocabulary/valueset-service-request-status.json, input/vocabulary/valueset-us-core-service-request-category.json
=> Added valuesets for Service Request

input/vocabulary/valueset-location-mode.json, input/vocabulary/valueset-location-physical-type.json, input/vocabulary/valueset-location-status.json, input/vocabulary/valueset-operationalStatus.json, input/vocabulary/valueset-service-delivery-location-role-type.json
=> Value sets for the Location profile

input/vocabulary/valueset-questionnaire-answers-status.json
@enjoysparkling  , Hi Matt, Kindly review the pull request.
=> Added Valueset Questionnaire-answers-status

input/resources/StructureDefinition-profile-SignalHealthcareService.json
1. Added slice under type element
2. Bound signal-healthcare-service category to HealthcareService.category
=> Updated Healthcare Service profile

input/resources/StructureDefinition-profile-SignalUSCoreEncounter.json
@enjoysparkling Hi Matt, I have added the profile for US Core Encounter and bound the valuesets, I have not touched the modifiers as you are planning on creating a separate model.
=> Added profile US Core Encounter

input/vocabulary/us-core-screening-assessment-observation-category.json
=> Value sets for the US Core Observation Screening Assessment Profile

input/resources/StructureDefinition-profile-SignalEpisodeOfCare.json
Added profile Signal Episode Of Care
Bound healthcare service type value set to EpisodeOfCare.type
=> Added profile SignalEpisodeOfCare

input/vocabulary/valueset-condition-clinical-status.json, input/vocabulary/valueset-condition-severity.json, input/vocabulary/valueset-condition-verification-status.json, input/vocabulary/valueset-us-core-problem-or-health-concern.json, input/vocabulary/valueset-us-core-screening-assessment-condition-category.json
=> Added valuesets for Condition Problems

input/vocabulary/valueset-observation-category.json, input/vocabulary/valueset-reference-range-applies-to.json, input/vocabulary/valueset-reference-range-meaning.json, input/vocabulary/valueset-us-core-simple-observation-category.json, input/vocabulary/valuset-data-absent-reason.json, input/vocabulary/valuset-observation-status.json
=> Value sets for the Simple Observation profile

input/vocabulary/codesystem-organization-type.json, input/vocabulary/valueset-organization-type.json
Updated Provider Agency to VS and CS on Organization Type. Kindly review @enjoysparkling
=> Updated Provider Agency to Value Set and Code System on Organization Type

input/resources/StructureDefinition-profile-SignalUSCoreServiceRequest.json
Added profile Signal US Core Service Request
Bound Service Type from HealthCare Service profile to category:us-core slice
=> Added profile Signal US Core Service Request

input/resources/StructureDefinition-profile-SignalEpisodeOfCare.json
1. Modified id, name, title, url
2. Added slices program and services to type element
=> Added requested changes for EpisodeOfCare

input/vocabulary/valueset-account-status.json, input/vocabulary/valueset-account-type.json
=> Value sets for the Account profile

input/vocabulary/valueset-coverage-class-code.json, input/vocabulary/valueset-coverage-copay-type-code.json, input/vocabulary/valueset-coverage-financial-exception.json, input/vocabulary/valueset-financial-resources-status-code.json, input/vocabulary/valueset-subscriber-relationship.json
=> Added valuesets for coverage

input/vocabulary/codesystem-signal-region.json, input/vocabulary/valueset-signal-region.json
Valueset and CodeSystem for the Signal-Region . Kindly review @enjoysparkling
=> Valueset and CodeSystem for the Signal-Region

input/vocabulary/codesystem-place-of-service.json, input/vocabulary/valueset-place-of-service.json
@enjoysparkling  Value Set and Code system for Place of Service is updated. Kindly review.
=> Value Set and Code system for Place of Service

input/resources/StructureDefinition-profile-SignalServiceRequest.json
Updated the StructureDefinition-profile-SignalServiceRequest.json. 
Review Required. 
@arunsundar-m  @vijayrajthangaraj
=> Updated StructureDefinition-profile-SignalServiceRequest.

input/resources/StructureDefinition-profile-SignalLocation.json
Binding Place of Service to Location.type valueset. Kindly review @arunsundar-m
=> Binding Place of Service to Location.type valueset

input/vocabulary/codesystem-contact-attempt-results.json, input/vocabulary/valueset-contact-attempt-results.json
Value set and Code system for Contact Attempt Results is created. Kindly review @arunsundar-m
=> Valueset and Codesystem for Contact Attempt Results

input/vocabulary/valueset-provider-taxonomy.json
Valueset is updated for Provider Taxonomy. Kindly review @arunsundar-m
=> Valueset Update for Provider Taxonomy

input/vocabulary/codesystem-healthcare-service-program.json, input/vocabulary/valueset-healthcare-service-program.json
Valueset and Codesystem is updated for the Program. Kindly review @arunsundar-m
=> Valueset update for Program

input/vocabulary/codesystem-healthcare-service-type.json, input/vocabulary/valueset-healthcare-service-type.json
Updated Value Set and CodeSystem for HealthCare Service Type. Kindly review @arunsundar-m
=> Updated valueset for HealthCare Service Type

input/resources/StructureDefinition-profile-SignalPatient.json
Added slice for Insurance Carrier
=> Added slice for Insurance Carrier

input/resources/StructureDefinition-profile-SignalOrganization.json
Added State Agency ID as identifier slice in Organization resource
=> Added StateAgencyID in Organization resource

input/resources/StructureDefinition-profile-SignalPatient.json
Added Trails ID and Household ID as a slice to identifier in Patient.
=> Added Trails ID and Household ID

input/vocabulary/valueset-chargeitem-status.json
Created the **chargeitem-status** valueset.
**Accountstatus** and **Invoicestatus** valueset are already deployed in the main as part of previous bulk deployment.
=> Created the chargeitem-status valueset

input/vocabulary/codesystem-progress-made-towards-goals.json, input/vocabulary/valueset-progress-made-towards-goals.json
Valueset for Progress Report. Kindky review @arunsundar-m
=> Valueset for Progress Report

input/vocabulary/codesystem-questionnaire-dacods-admission-route-of-administration.json, input/vocabulary/codesystem-questionnaire-dacods-client-disability.json, input/vocabulary/codesystem-questionnaire-dacods-clinician-diagnostic-impression.json, input/vocabulary/codesystem-questionnaire-dacods-discharge-route-of-administration.json, input/vocabulary/codesystem-questionnaire-dacods-health-insurance-status.json, input/vocabulary/codesystem-questionnaire-dacods-secondary-tertiary-drug-type-code.json, input/vocabulary/codesystem-questionnaire-dacods-source-of-payment-for-treatment.json, input/vocabulary/codesystem-questionnaire-dacods-tobacco-use.json, input/vocabulary/codesystem-questionnaire-dacods-yes-no-na.json, input/vocabulary/valueset-questionnaire-dacods-admission-route-of-administration.json, input/vocabulary/valueset-questionnaire-dacods-client-disability.json, input/vocabulary/valueset-questionnaire-dacods-clinician-diagnostic-impression.json, input/vocabulary/valueset-questionnaire-dacods-discharge-route-of-administration.json, input/vocabulary/valueset-questionnaire-dacods-health-insurance-status.json, input/vocabulary/valueset-questionnaire-dacods-secondary-tertiary-drug-type-code.json, input/vocabulary/valueset-questionnaire-dacods-source-of-payment-for-treatment.json, input/vocabulary/valueset-questionnaire-dacods-tobacco-use.json
Valueset and Code systems are updated for DACODS admission and Discharge. Kindly review @arunsundar-m
=> Valueset and Codesystem update - DACODS

input/vocabulary/codesystem-healthcare-service-type.json, input/vocabulary/valueset-healthcare-service-type.json
Update Valueset and Code system is updated Healthcare service. Kindly review @arunsundar-m
=> Update Valueset and Code system for Healthcare service

input/vocabulary/codesystem-healthcare-service-type.json, input/vocabulary/valueset-healthcare-service-type.json
Updated the Code for Cymhta as part of Forge Validation error. @arunsundar-m  Kindly review
**"Instance failed constraint csd-1 "Within a code system definition, all the codes SHALL be unique" - codesystem-healthcare-service-type"**
=> Updated the Code for Cymhta

guides/Signal-Implementation-Guide/Index/Terminology/Custom-Terminology.page.md, guides/Signal-Implementation-Guide/Index/Terminology/Questionnaire-Terminology.page.md
Documentation for Survey Questionnaire and Custom Value set is completed. Kindly review.
=> Documentation for Survey Questionnaire and Custom Value set.

input/vocabulary/valueset-questionnaire-dacods-reason-for-discharge.json
Valueset URL is updated for the questionnaire reason for discharge valueset. Kindly review @arunsundar-m
=> URL update - valueset-questionnaire-dacods-reason-for-discharge

input/resources/SearchParameter-EncounterEndDate.json, input/resources/SearchParameter-InvoiceBillIdentifier.json, input/resources/SearchParameter-QuestionnaireResponse.json
Search Parameter for Invoicebillid, questionnaire, encounter-end-date is created. Need review @arunsundar-m
=> Search Parameter for Invoicebillid, questionnaire, encounter-end-date

input/resources/StructureDefinition-extension-SignalAdminMultiplierRate.json, input/resources/StructureDefinition-extension-SignalEffectiveDate.json, input/resources/StructureDefinition-extension-SignalInvoiceTimePeriod.json, input/resources/StructureDefinition-profile-SignalAccount.json, input/resources/StructureDefinition-profile-SignalInvoice.json
Updated Structure definition for Invoice/Account Resources. Kindly review @arunsundar-m
=> Updated Structure definition for Invoice/Account Resources

input/vocabulary/codesystem-healthcare-service-type.json, input/vocabulary/valueset-healthcare-service-type.json
Updated the Healthcare services valueset and code system as per the new inputs given by signal. Kindly review @arunsundar-m
=> Updated the Healthcare services valueset and code system

input/resources/StructureDefinition-profile-SignalEncounter.json
Bind "reason for discharge" to Encounter profile.  Kindly review @arunsundar-m
=> Bind "reason for discharge" to Encounter profile

input/resources/StructureDefinition-extension-SignalInvoiceFinalBillDate.json, input/resources/StructureDefinition-extension-SurveyStateActivityStatus.json, input/resources/StructureDefinition-profile-SignalQuestionnaireResponse.json
Created Structure definition for Invoice and Questionnaire Response. Kindly review @arunsundar-m
=> Create Structure definition for Invoice and Questionnaire Response

input/vocabulary/codesystem-questionnaire-ccars-enrollment-payer.json, input/vocabulary/codesystem-questionnaire-dacods-source-of-payment-for-treatment.json, input/vocabulary/valueset-questionnaire-ccars-enrollment-payer.json, input/vocabulary/valueset-questionnaire-dacods-source-of-payment-for-treatment.json
To Update "State ID" instead of "Medicaid" for the Survey Questionnaire. Kindly Approve @vijayrajthangaraj to implement the changes.
Reference Ticket:
https://signalbhn.atlassian.net/jira/software/projects/ITM/boards/14?assignee=712020%3A46fe5b1e-8baf-4cdc-ac84-f86563c8e4b3%2C712020%3A4034ff95-5751-441a-9a90-3262042f5335&selectedIssue=ITM-4413
=> Update "State ID" instead of "Medicaid" for the Survey Questionnaire

input/resources/SearchParameter-DocumentReferenceMasterIdentifier.json, input/resources/StructureDefinition-extension-SignalDocID.json, input/vocabulary/codesystem-signal-state-activity-status.json, input/vocabulary/valueset-signal-state-activity-status.json
QA deployment for Sprint 28.  Kindly review @arunsundar-m 
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/GOKULK~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/GOKULK~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>
</style>
</head>
<body link="#467886" vlink="#96607D">
Resource   Type | File Name | Details
-- | -- | --
Valueset | valueset-state-activity-status | Create New Valueset
Codesystem | codesystem-state-activity-status | Create New …
=> QA deployment for Sprint 28

input/vocabulary/codesystem-reason-for-discharge.json, input/vocabulary/valueset-reason-for-discharge.json
Updated the ValueSet and CodeSystem for "reason for discharge". Kindly review @arunsundar-m
=> ValueSet and CodeSystem update for reason for discharge

input/vocabulary/codesystem-signal-filerepo-classification.json, input/vocabulary/valueset-signal-filerepo-classification.json
Updated the ValueSet and CodeSystem for Filerepo Classification as per the Signal CR. Kindly review @arunsundar-m
=> Updated the VS and CS for Filerepo Classification

input/vocabulary/valueset-provider-taxonomy.json
Taxonomy valueset is updated as per signals requirement.  Kindly review @arunsundar-m
=> Updated Taxonomy valueset

input/vocabulary/codesystem-healthcare-service-type.json, input/vocabulary/codesystem-reason-for-discharge.json, input/vocabulary/codesystem-signal-filerepo-classification.json, input/vocabulary/valueset-healthcare-service-type.json, input/vocabulary/valueset-reason-for-discharge.json, input/vocabulary/valueset-signal-filerepo-classification.json
Valuesets and Code system's are updated as per the Signal CR's. Kindly review @arunsundar-m .
=> Valuesets and Code system's are updated as per Signal CR's

input/resources/StructureDefinition-profile-SignalOrganization.json
Updated the Structure URL for Primary Location ID.  Kindly review @arunsundar-m 
**Replaced**
https://signalbhn.org/fhir/sid/edi/primary-location-id
**with**
https://signalbhn.org/fhir/sid/edi/provider-location-id
=> Updated the Structure URL for Primary Location ID

input/resources/StructureDefinition-extension-SignalInvoiceLocationID.json, input/resources/StructureDefinition-extension-SignalPayer.json, input/resources/StructureDefinition-extension-SignalPayerAccount.json, input/resources/StructureDefinition-extension-SignalPayerAccountEffectiveDate.json, input/resources/StructureDefinition-extension-SignalPayerEffectiveTimePeriod.json, input/resources/StructureDefinition-extension-SignalProcedureCodeApproved.json, input/resources/StructureDefinition-extension-SignalProgramReferred.json, input/resources/StructureDefinition-extension-SignalServiceReferred.json, input/resources/StructureDefinition-extension-SignalServiceRequestAuthorizedAmount.json, input/resources/StructureDefinition-extension-SignalServiceRequestDateOfReferral.json, input/resources/StructureDefinition-extension-SignalServiceRequestGuardian.json, input/resources/StructureDefinition-extension-SignalServiceRequestNoOfUnits.json, input/resources/StructureDefinition-extension-SignalServiceRequestParentFee.json, input/resources/StructureDefinition-extension-SignalServiceRequestParentFlatRate.json, input/resources/StructureDefinition-extension-SignalServiceRequestPatient.json, input/resources/StructureDefinition-extension-SignalServiceRequestProvider.json, input/resources/StructureDefinition-extension-SignalServiceRequestReferringOrg.json, input/resources/StructureDefinition-extension-SignalServiceRequestTrailsClientID.json, input/resources/StructureDefinition-extension-SignalServiceRequestTrailsCountyHouseholdID.json, input/resources/StructureDefinition-extension-SignalServiceRequestTrailsID.json
To add Extension for Service Request Profile on behalf of the referral mapping. Kindly approve @arunsundar-m
=> Add Extension for Service Request Profile

input/vocabulary/codesystem-provider-taxonomy-na.json, input/vocabulary/valueset-provider-taxonomy.json
Updated the N/A drop down in value set and CodeSystem for Provider Taxonomy. Kindly review @arunsundar-m
=> N/A drop down update for Provider Taxonomy

input/resources/SearchParameter-EncounterPeriodEndDate.json, input/resources/SearchParameter-EncounterPeriodStartDate.json, input/resources/SearchParameter-ServiceRequestClientFirstName.json, input/resources/SearchParameter-ServiceRequestClientLastName.json, input/resources/SearchParameter-ServiceRequestClientName.json, input/resources/StructureDefinition-extension-ProgramEffectiveDate.json, input/resources/StructureDefinition-extension-RegionEffectiveDate.json
Created Custom search Parameter for Encounter & Extensions for Location, HealthCare service effective date. Kindly approve @arunsundar-m
=> Create Custom search Parameter

input/resources/StructureDefinition-extension-SignalQualification.json
Updated structure definition by adding up extensions for license type.
=> Updated structure definition by adding up extensions for license type

input/resources/SearchParameter-CommunicationNotes.json, input/resources/SearchParameter-PayerAccountEffectiveEndDate.json, input/resources/SearchParameter-PayerAccountEffectiveStartDate.json, input/resources/SearchParameter-PayerEffectiveEndDate.json, input/resources/SearchParameter-PayerEffectiveStartDate.json, input/vocabulary/codesystem-bhe-endorsement-category.json, input/vocabulary/codesystem-bhe-facility-type.json, input/vocabulary/codesystem-bhe-population-served.json, input/vocabulary/codesystem-carr-level.json, input/vocabulary/codesystem-csl-drug-schedule.json, input/vocabulary/codesystem-provider-agency-approval.json, input/vocabulary/codesystem-provider-agency-bhe-designation.json, input/vocabulary/codesystem-signal-license-type.json, input/vocabulary/valueset-bhe-endorsement-category.json, input/vocabulary/valueset-bhe-facility-type.json, input/vocabulary/valueset-bhe-population-served.json, input/vocabulary/valueset-carr-level.json, input/vocabulary/valueset-csl-drug-schedule.json, input/vocabulary/valueset-provider-agency-approval.json, input/vocabulary/valueset-provider-agency-bhe-designation.json, input/vocabulary/valueset-signal-ethnicity-list.json, input/vocabulary/valueset-signal-license-type.json
Created VS and CS for License Type & Created Search Parameter. Please review @arunsundar-m
=> Create VS and CS for License Type & Create Search Parameter

input/resources/StructureDefinition-profile-SignalLocation.json, input/resources/StructureDefinition-profile-SignalOrganization.json, input/vocabulary/valueset-provider-taxonomy.json
Updated Existing Structure Definition and Valueset. Please review @arunsundar-m
=> Updated Existing Structure Definition

input/resources/SearchParameter-ReferralProgram.json, input/resources/SearchParameter-ServiceRequestProviderAgencyID.json, input/resources/SearchParameter-ServiceRequestSupportingInfo.json, input/resources/StructureDefinition-extension-AdmissionUniqueID.json, input/resources/StructureDefinition-extension-AgencyCode.json, input/resources/StructureDefinition-extension-DACODSExtractionStatus.json, input/resources/StructureDefinition-extension-DACODSExtractionTime.json, input/resources/StructureDefinition-extension-EncounterCreated.json, input/resources/StructureDefinition-extension-EncounterExtractionStatus.json, input/resources/StructureDefinition-extension-EncounterExtractionTime.json, input/resources/StructureDefinition-extension-EncounterLastUpdated.json, input/resources/StructureDefinition-extension-EncounterReportGenerationStatus.json, input/vocabulary/codesystem-signal-procedure-code.json, input/vocabulary/codesystem-special-studies-code.json, input/vocabulary/valueset-special-studies-code.json
DM team to deploy the Valueset, code system, Search Parameter & Structure definition on behalf of the QA migration to UAT and PROD Environment.
Kindly review @arunsundar-m
=> Valueset, code system,  & Structure definition deployment
